INSERT INTO faces (face, uses) VALUES ("¯\_(ツ)_/¯", 0);
INSERT INTO faces (face, uses) VALUES ("ಠ⌣ಠ", 0);
INSERT INTO faces (face, uses) VALUES ("( ͡° ͜ʖ ͡°)", 0);
INSERT INTO faces (face, uses) VALUES ("ಠ_ಠ", 0);
INSERT INTO faces (face, uses) VALUES ("ヽ༼ຈل͜ຈ༽ﾉ", 0);
INSERT INTO faces (face, uses) VALUES ("༼ つ ◕_◕ ༽つ", 0);
INSERT INTO faces (face, uses) VALUES ("(ಥ_ಥ)", 0);
INSERT INTO faces (face, uses) VALUES ("ʕ•ᴥ•ʔ", 0);
INSERT INTO faces (face, uses) VALUES ("(づ｡◕‿‿◕｡)づ", 0);
INSERT INTO faces (face, uses) VALUES ("(☞ﾟヮﾟ)☞ ☜(ﾟヮﾟ☜)", 0);
INSERT INTO faces (face, uses) VALUES ("(╯°□°)╯︵ ʞooqǝɔɐɟ", 0);
INSERT INTO faces (face, uses) VALUES ("﴾͡๏̯͡๏﴿ O'RLY?", 0);
INSERT INTO faces (face, uses) VALUES ("(╯°□°）╯︵ ┻━┻", 0);
INSERT INTO faces (face, uses) VALUES ("(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧", 0);
INSERT INTO faces (face, uses) VALUES ("| (• ◡•)| (❍ᴥ❍ʋ)", 0);
INSERT INTO faces (face, uses) VALUES ("ლ(ಠ益ಠლ)", 0);
INSERT INTO faces (face, uses) VALUES ("(ง'̀-'́)ง", 0);
INSERT INTO faces (face, uses) VALUES ("┬┴┬┴┤(･_├┬┴┬┴", 0);
INSERT INTO faces (face, uses) VALUES ("ಠ╭╮ಠ", 0);
INSERT INTO faces (face, uses) VALUES ("(•_•) ( •_•)&gt;⌐■-■ (⌐■_■)", 0);
INSERT INTO faces (face, uses) VALUES ("ಥ_ಥ", 0);
INSERT INTO faces (face, uses) VALUES ("(☞ﾟ∀ﾟ)☞", 0);
INSERT INTO faces (face, uses) VALUES ("(づ￣ ³￣)づ", 0);
INSERT INTO faces (face, uses) VALUES ("(ノಠ益ಠ)ノ彡┻━┻", 0);
INSERT INTO faces (face, uses) VALUES ("ᕙ(⇀‸↼‶)ᕗ", 0);
INSERT INTO faces (face, uses) VALUES ("(ᵔᴥᵔ)", 0);
INSERT INTO faces (face, uses) VALUES ("┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻", 0);
INSERT INTO faces (face, uses) VALUES ("[̲̅$̲̅(̲̅5̲̅)̲̅$̲̅]", 0);
INSERT INTO faces (face, uses) VALUES ("(._.) ( l: ) ( .-. ) ( :l ) (._.)", 0);
INSERT INTO faces (face, uses) VALUES ("(͡° ͜ʖ ͡°)", 0);
INSERT INTO faces (face, uses) VALUES ("(•◡•) /", 0);
INSERT INTO faces (face, uses) VALUES ("ヾ(⌐■_■)ノ♪", 0);
INSERT INTO faces (face, uses) VALUES ("(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧ ✧ﾟ･: *ヽ(◕ヮ◕ヽ)", 0);
INSERT INTO faces (face, uses) VALUES ("（╯°□°）╯︵( .o.)", 0);
INSERT INTO faces (face, uses) VALUES ("♥‿♥", 0);
INSERT INTO faces (face, uses) VALUES ("(｡◕‿‿◕｡)", 0);
INSERT INTO faces (face, uses) VALUES ("▄︻̷̿┻̿═━一", 0);
INSERT INTO faces (face, uses) VALUES ("┌( ಠ_ಠ)┘", 0);
INSERT INTO faces (face, uses) VALUES ("(°ロ°)☝", 0);
INSERT INTO faces (face, uses) VALUES ("ლ(´ڡ`ლ)", 0);
INSERT INTO faces (face, uses) VALUES ("┬──┬ ノ( ゜-゜ノ)", 0);
INSERT INTO faces (face, uses) VALUES ("ʘ‿ʘ", 0);
INSERT INTO faces (face, uses) VALUES ("⊙▃⊙", 0);
INSERT INTO faces (face, uses) VALUES ("¯(°_o)/¯", 0);
INSERT INTO faces (face, uses) VALUES ("ლ,ᔑ•ﺪ͟͠•ᔐ.ლ", 0);
INSERT INTO faces (face, uses) VALUES ("(ಠ_ಠ)", 0);
INSERT INTO faces (face, uses) VALUES ("ᄽὁȍ ̪ őὀᄿ", 0);
INSERT INTO faces (face, uses) VALUES ("◕‿↼", 0);
INSERT INTO faces (face, uses) VALUES ("☜(⌒▽⌒)☞", 0);
INSERT INTO faces (face, uses) VALUES ("⊙﹏⊙", 0);
INSERT INTO faces (face, uses) VALUES ("(｡◕‿◕｡)", 0);
INSERT INTO faces (face, uses) VALUES ("◉_◉", 0);
INSERT INTO faces (face, uses) VALUES ("Ƹ̵̡Ӝ̵̨̄Ʒ", 0);
INSERT INTO faces (face, uses) VALUES ("(´・ω・`)", 0);
INSERT INTO faces (face, uses) VALUES ("⚆ _ ⚆", 0);
INSERT INTO faces (face, uses) VALUES ("┬─┬﻿ ︵ /(.□. ）", 0);
INSERT INTO faces (face, uses) VALUES ("(ಥ﹏ಥ)", 0);
INSERT INTO faces (face, uses) VALUES ("(•ω•)", 0);
INSERT INTO faces (face, uses) VALUES ("(¬‿¬)", 0);
INSERT INTO faces (face, uses) VALUES ("╚(ಠ_ಠ)=┐", 0);
INSERT INTO faces (face, uses) VALUES ("ಠ_ಥ", 0);
INSERT INTO faces (face, uses) VALUES ("⌐╦╦═─", 0);
INSERT INTO faces (face, uses) VALUES ("(ʘᗩʘ')", 0);
INSERT INTO faces (face, uses) VALUES ("ب_ب", 0);
INSERT INTO faces (face, uses) VALUES ("｡◕‿‿◕｡", 0);
INSERT INTO faces (face, uses) VALUES ("┬─┬ノ( º _ ºノ)", 0);
INSERT INTO faces (face, uses) VALUES ("◔̯◔", 0);
INSERT INTO faces (face, uses) VALUES ("(´・ω・)っ由", 0);
INSERT INTO faces (face, uses) VALUES ("(ಠ⌣ಠ)", 0);
INSERT INTO faces (face, uses) VALUES ("(/) (°,,°) (/)", 0);
INSERT INTO faces (face, uses) VALUES ("☉_☉", 0);
INSERT INTO faces (face, uses) VALUES ("(ʘ‿ʘ)", 0);
INSERT INTO faces (face, uses) VALUES ("(─‿‿─)", 0);
INSERT INTO faces (face, uses) VALUES ("(；一_一)", 0);
INSERT INTO faces (face, uses) VALUES ("๏̯͡๏﴿", 0);
INSERT INTO faces (face, uses) VALUES ("٩◔̯◔۶", 0);
INSERT INTO faces (face, uses) VALUES ("°Д°", 0);
INSERT INTO faces (face, uses) VALUES ("(⊙ω⊙)", 0);
INSERT INTO faces (face, uses) VALUES ("(ó ì_í)=óò=(ì_í ò)", 0);
INSERT INTO faces (face, uses) VALUES ("(◕‿◕)", 0);
INSERT INTO faces (face, uses) VALUES ("( ﾟヮﾟ)", 0);
INSERT INTO faces (face, uses) VALUES ("｡◕‿◕｡", 0);
INSERT INTO faces (face, uses) VALUES ("◕‿◕", 0);
INSERT INTO faces (face, uses) VALUES ("( ⚆ _ ⚆ )", 0);
INSERT INTO faces (face, uses) VALUES ("ಠ~ಠ", 0);
INSERT INTO faces (face, uses) VALUES ("ಠ‿ಠ", 0);
INSERT INTO faces (face, uses) VALUES ("ರ_ರ", 0);
INSERT INTO faces (face, uses) VALUES ("☼.☼", 0);
INSERT INTO faces (face, uses) VALUES ("〆(・∀・＠)", 0);
INSERT INTO faces (face, uses) VALUES ("◔ ⌣ ◔", 0);
INSERT INTO faces (face, uses) VALUES ("(ಠ‿ಠ)", 0);
INSERT INTO faces (face, uses) VALUES ("ಠoಠ", 0);
INSERT INTO faces (face, uses) VALUES ("≧☉_☉≦", 0);
INSERT INTO faces (face, uses) VALUES ("(¬_¬)", 0);
INSERT INTO faces (face, uses) VALUES ("¬_¬", 0);
INSERT INTO faces (face, uses) VALUES ("(･.◤)", 0);
INSERT INTO faces (face, uses) VALUES ("(^̮^)", 0);
INSERT INTO faces (face, uses) VALUES ("&gt;_&gt;", 0);
INSERT INTO faces (face, uses) VALUES ("^̮^", 0);
INSERT INTO faces (face, uses) VALUES ("(~_^)", 0);
INSERT INTO faces (face, uses) VALUES (":')", 0);
INSERT INTO faces (face, uses) VALUES ("&lt;_&lt;", 0);
INSERT INTO faces (face, uses) VALUES ("=U", 0);
